import { Injectable } from '@angular/core';
import { Observable, of } from '../rxjs-exports';
import { TopMenu } from './model';

@Injectable()
export class NavigationDataService {
  constructor() {}

  getMenus(): Observable<TopMenu[]> {
    return of([
      {
        TopMenuId: 1,
        Location: 'finance',
        Name: 'Finance',
        Icon: 'fa-solid fa-indian-rupee-sign',
        Direction: 'horizontal',
        Description:
          'Finance module provides ledger for detailed record of all the transactions and we will have statistics reports around expenditures.',
        SortOrder: -1,
        SubMenus: [
          {
            SubMenuId: 1,
            Description: 'Ledger',
            Icon: 'fa-solid fa-book',
            IsDisabled: false,
            Location: 'finance/ledger',
            ObjectTypeName: 'ledger',
            TopMenuId: 1,
            SortOrder: 2,
          },
          {
            SubMenuId: 2,
            Description: 'Tax Collection',
            Icon: 'fa-solid fa-receipt',
            IsDisabled: false,
            Location: 'finance/tax-collection',
            ObjectTypeName: 'TaxCollection',
            TopMenuId: 1,
            SortOrder: 3,
          },
          {
            SubMenuId: 3,
            Description: 'Balance Sheet',
            Icon: 'fa-solid fa-scale-balanced',
            IsDisabled: false,
            Location: 'finance/balance-sheet',
            ObjectTypeName: 'BalanceSheet',
            TopMenuId: 1,
            SortOrder: 4,
          },
        ],
      },
      {
        TopMenuId: 2,
        Location: 'complaint',
        Name: 'Complaint',
        Icon: 'fa-solid fa-arrow-right-to-bracket',
        Direction: 'horizontal',
        Description:
          'One-stop platform for citizens to seek redressal of their grievances and provide feedback for improvements.',
        SortOrder: 2,
        SubMenus: [
          {
            SubMenuId: 1,
            Description: 'Status',
            Icon: 'fa-solid fa-bars-staggered',
            IsDisabled: false,
            Location: 'complaint/status',
            ObjectTypeName: 'Status',
            TopMenuId: 2,
            SortOrder: 2,
          },
          {
            SubMenuId: 2,
            Description: 'Report New',
            Icon: 'fa-solid fa-file-circle-plus',
            IsDisabled: false,
            Location: 'complaint/report-new',
            ObjectTypeName: 'ReportNew',
            TopMenuId: 2,
            SortOrder: 3,
          },
        ],
      },
      {
        TopMenuId: 3,
        Location: 'events',
        Name: 'Events',
        Icon: 'fa-regular fa-calendar-days',
        Direction: 'horizontal',
        Description:
          'Upcoming events and announcements will placed with schedule, purpose and related informations.',
        SortOrder: 3,
        SubMenus: [
          {
            SubMenuId: 1,
            Description: 'Events',
            Icon: 'fa-solid fa-calendar-day',
            IsDisabled: false,
            Location: 'events/events',
            ObjectTypeName: 'Events',
            TopMenuId: 3,
            SortOrder: 2,
          },
          {
            SubMenuId: 2,
            Description: 'Announcements',
            Icon: 'fa-solid fa-volume-high',
            IsDisabled: false,
            Location: 'events/announcements',
            ObjectTypeName: 'Announcements',
            TopMenuId: 3,
            SortOrder: 3,
          },
        ],
      },
      {
        TopMenuId: 4,
        Location: 'gallery',
        Name: 'Gallery',
        Icon: 'fa-regular fa-images',
        Direction: 'vertical',
        Description:
          'A gallery with photos and videos to share memorable memory and achievements.',
        SortOrder: 4,
        SubMenus: [
          {
            SubMenuId: 1,
            Description: 'All Photos',
            Icon: 'fa-solid fa-image',
            IsDisabled: false,
            Location: 'gallery/all-photos',
            ObjectTypeName: 'AllPhotos',
            TopMenuId: 4,
            SortOrder: 2,
          },
          {
            SubMenuId: 2,
            Description: 'All Videos',
            Icon: 'fa-solid fa-video',
            IsDisabled: false,
            Location: 'gallery/all-vidoes',
            ObjectTypeName: 'AllVideos',
            TopMenuId: 4,
            SortOrder: 3,
          },
          {
            SubMenuId: 3,
            Description: 'Event Photos',
            Icon: 'fa-solid fa-calendar-days',
            IsDisabled: false,
            Location: 'gallery/event-photos',
            ObjectTypeName: 'EventPhotos',
            TopMenuId: 4,
            SortOrder: 4,
          },
          {
            SubMenuId: 4,
            Description: 'Event Videos',
            Icon: 'fa-solid fa-calendar-days',
            IsDisabled: false,
            Location: 'gallery/event-vidoes',
            ObjectTypeName: 'EventVideos',
            TopMenuId: 4,
            SortOrder: 5,
          },
        ],
      },
      {
        TopMenuId: 5,
        Location: 'egovernance',
        Name: 'eGovernance',
        Icon: 'fa-solid fa-globe',
        Direction: 'horizontal',
        Description:
          'E-governance is most cutting-edge efforts to develop effective governance. Provides connectivity to all e-governance aspects.',
        SortOrder: 5,
        SubMenus: [],
      },
      {
        TopMenuId: 6,
        Location: 'analytics',
        Name: 'Analytics',
        Icon: 'fa-regular fa-snowflake',
        Direction: 'vertical',
        Description:
          'Systematic computational analysis of data or statistics presented as report and graphs.',
        SortOrder: 6,
        SubMenus: [
          {
            SubMenuId: 1,
            Description: 'By Gender',
            Icon: 'fa-solid fa-venus-mars',
            IsDisabled: false,
            Location: 'analytics/by-gender',
            ObjectTypeName: 'ByGender',
            TopMenuId: 6,
            SortOrder: 2,
          },
          {
            SubMenuId: 2,
            Description: 'By Qualifications',
            Icon: 'fa-solid fa-graduation-cap',
            IsDisabled: false,
            Location: 'analytics/by-qualifications',
            ObjectTypeName: 'ByQualifications',
            TopMenuId: 6,
            SortOrder: 3,
          },
          {
            SubMenuId: 3,
            Description: 'By Vehicles',
            Icon: 'fa-solid fa-car-side',
            IsDisabled: false,
            Location: 'analytics/by-vehicles',
            ObjectTypeName: 'ByVehicles',
            TopMenuId: 6,
            SortOrder: 4,
          },
          {
            SubMenuId: 4,
            Description: 'By Tax Collection',
            Icon: 'fa-solid fa-file-invoice-dollar',
            IsDisabled: false,
            Location: 'analytics/by-tax-collection',
            ObjectTypeName: 'ByTaxCollection',
            TopMenuId: 6,
            SortOrder: 5,
          },
        ],
      },
      {
        TopMenuId: 7,
        Location: 'admin',
        Name: 'Admin',
        Icon: 'fa-brands fa-redhat',
        Direction: 'vertical',
        Description:
          'Provides feature to onboard new panchayat and users. Offers features to manage - Access, Data, Qualifications, Vehicle details.',
        SortOrder: 7,
        SubMenus: [
          {
            SubMenuId: 1,
            Description: 'Role',
            Icon: 'fa-solid fa-user-group',
            IsDisabled: false,
            Location: 'admin/role',
            ObjectTypeName: 'Role',
            TopMenuId: 7,
            SortOrder: 2,
          },
          {
            SubMenuId: 2,
            Description: 'Role Access',
            Icon: 'fa-solid fa-user-shield',
            IsDisabled: false,
            Location: 'admin/role-access',
            ObjectTypeName: 'RoleAccess',
            TopMenuId: 7,
            SortOrder: 3,
          },
          {
            SubMenuId: 3,
            Description: 'House',
            Icon: 'fa-regular fa-building',
            IsDisabled: false,
            Location: 'admin/house',
            ObjectTypeName: 'House',
            TopMenuId: 7,
            SortOrder: 4,
          },
          {
            SubMenuId: 4,
            Description: 'User',
            Icon: 'fa-solid fa-list-check',
            IsDisabled: false,
            Location: 'admin/users',
            ObjectTypeName: 'User',
            TopMenuId: 7,
            SortOrder: 5,
          },
          {
            SubMenuId: 5,
            Description: 'Qualification',
            Icon: 'fa-solid fa-graduation-cap',
            IsDisabled: false,
            Location: 'admin/qualifications',
            ObjectTypeName: 'Qualification',
            TopMenuId: 7,
            SortOrder: 6,
          },
          {
            SubMenuId: 6,
            Description: 'Vehicle',
            Icon: 'fa-solid fa-car-side',
            IsDisabled: false,
            Location: 'admin/vehicles',
            ObjectTypeName: 'Vehicle',
            TopMenuId: 7,
            SortOrder: 7,
          },
          {
            SubMenuId: 7,
            Description: 'Panchayat',
            Icon: 'fa-solid fa-location-dot',
            IsDisabled: false,
            Location: 'admin/panchayat',
            ObjectTypeName: 'Panchayat',
            TopMenuId: 7,
            SortOrder: 8,
          },
          {
            SubMenuId: 8,
            Description: 'Employees',
            Icon: 'fa-regular fa-address-card',
            IsDisabled: false,
            Location: 'admin/employees',
            ObjectTypeName: 'Employees',
            TopMenuId: 7,
            SortOrder: 9,
          },
        ],
      },
    ]);
  }
}
